# Governing Documents

Clerks should be aware of the governing documents of their church and know how to access them when necessary.

## Church Government

Each church within Evangel Presbytery is governed by:

1. Evangel Presbytery's [Book of Church Order (BCO)](https://evangel.pressbooks.com) and 
2. its own bylaws. 

Whenever the bylaws of a particular church and the BCO conflict, the BCO takes precedence. However, it is common for church bylaws to be *more* specific than the BCO in areas where they do not conflict. For example, many churches specify that members must be a certain age to vote, whereas the BCO is silent on that question. If a church finds that its bylaws are in conflict with the BCO, it should work to bring those bylaws into conformity with the BCO.

The process for amending Evangel's BCO can be found in [BCO 29](https://evangel.pressbooks.com/chapter/29-amending-the-constitution-of-the-church/).

Evangel Presbytery itself is also governed by [its own bylaws](https://bylaws.evangelpresbytery.com/index.html), which mostly pertain to the presbytery's governance of its own procedures, though some of its provisions necessarily affect member churches as far as their participation in the presbytery is concerned.

## Civil Government

1. Each particular church must file **articles of incorporation** in the state where it resides. **[REQUIRED]**
2. Most states **exempt** churches and other non-profits from paying **sales tax**, but that exemption must be applied for and granted, and often renewed every year. Check with your own state's laws. **[OPTIONAL, BUT RECOMMENDED]**
3. Churches are automatically granted **[501(c)(3)]{.nb} status** by the IRS without any forms being filed whatsoever. Still, many churches elect to officially apply for [501(c)(3)]{.nb} status. One reason is that many companies offer benefits to non-profits which are not made available unless the church can produce an IRS determination letter as evidence of their non-profit status. **[OPTIONAL]**

## Church Policies

It is common for churches to have internal policies governing many different areas. Depending on the needs of our church, you may consider establishing policies for the following topics:

* childcare
* building use
* weddings
* staff absences/vacations
* *etc.*

## Position Papers

Just as Evangel Presbytery itself has adopted [specific resolutions](https://evangelpresbytery.com/documents/), each particular church may adopt and publish their position on a given topic.
