# Keeping Minutes

Evangel Presbytery's official standards for keeping minutes can be found in [Appendix\ 1 of the presbytery's bylaws](https://docs.google.com/document/d/1WZ4PrWPCNPNsUEmfXLPNXCNJz5qaB09T3HXnCkPh2ak/edit?usp=sharing). The information included in this section of the handbook is intended to supplement the presbytery's standards without adding further requirements.

Meeting minutes must be kept with utmost care. They are the official record of the decisions of a deliberative body. Once approved, they are the final word on what happened and what was decided at a meeting. Good minutes help promote integrity and accountability, and they act as a practical reference for future discussions and decisions of the session. The keeping of minutes is also typically the stated clerk’s most consistent and frequent area of responsibility.

## Principles for Keeping Good Minutes

### 1. Clarity {-}

Put yourself in the shoes of a session member reading your minutes ten years from now. Will he have enough information to clearly understand what decision was made, who was involved, and why the decision was made?

### 2. Concision {-}

Minutes are intended to record essential information only. They should not be a detailed play-by-play of delibertaion. The most important thing to record in minutes is any official action taken by the session.

### 3. Consistency {-}

There are many different ways to approach spelling, punctuation, abbreviations, outline structure, etc. The most important thing is to be consistent in how you handle such matters of formatting and style. Consistency helps minutes to be more clear, and it makes minutes more useful as a reference. For example, it is common to use a computer program to search the minutes for all mentions of a particular name. Being careful to spell names correctly and consistently helps ensure that you will be able to find the information you need.

## What Minutes Should Be Kept?

A clerk of session should be sure to have a permanent record of both regular and special called meetings of the following groups:

* **The session**, a.k.a. the board of elders.
* **Session-appointed commissions**. "A Commission is authorized to deliberate upon and conclude the business referred to it. It shall keep a full record of its proceedings, which shall be submitted to the court appointing it, entered on its minutes, and regarded and treated as the action of the court" ([BCO 17.1](https://evangel.pressbooks.com/chapter/17-ecclesiastical-commissions/)).
* **The board of deacons**. While deacons' minutes do not need to be submitted to the presbytery for review, they do need to be submitted to the *session* ([BCO 11.4](https://evangel.pressbooks.com/chapter/11-the-deacon/)). The clerk of session will most often rely on the secretary of the board of deacons to keep minutes for deacons meetings, but it is still the clerk's responsibility to ensure these minutes are accurate, well organized, and available for review.
* **The congregation**. Because of the size of the body meeting, congregational meetings are often more formal in their proceedings than session meetings. Minutes for congregational meetings are just as important as session meetings and should adhere to the same principles as session minutes.

A church may have many committees that meet regularly, and many of those committees will choose to take minutes. However, it is not necessary for the clerk of session to have a permanent record of all committees' minutes.

## Where to Take Minutes

We strongly recommend taking and circulating minutes for review and approval in the body of an email.

- Email programs allow basic text formatting (bold, italics, lists, etc.) without the problems associated with attachments. Attachments clutter up hard drives and can't be searched as easily as email can be.
- Taking minutes in the body of an email helps reduce conflicting versions of minutes.

We recommend using a consistent pattern in subject lines of emails with minutes. It is best to include

* the church name (or abbreviation)
* the type of meeting and the name of the body meeting (e.g., "Session Meeting", "Congregational Meeting", etc.)
* the word "minutes"
* the date of the meeting
* the status of the minutes being circulated (e.g., "FOR REVIEW", "FOR APPROVAL", "CORRECTED" etc.)

For example:

> TPC Special Called Session Meeting Minutes 2022.03.30 – FOR REVIEW

Following a consistent pattern in subject lines will make it much easier to search for minutes in your email app.

## Adoption Process for Session Minutes

The following is a recommended (but not required) process for ensuring that minutes get properly reviewed and adopted by the session in a timely manner. After taking minutes…

1. **Edit and proofread the minutes shortly after the meeting.**
2. **Send edited minutes to the moderator for review and correction.** It is good for the clerk to work hard to understand the personality, working habits, and preferences of the moderator, so as to ensure the effectiveness of his leadership of the session. In general, the stated clerk should seek to accomplish any minutes-related tasks which are most helpful to the moderator. For example, it may be helpful for the clerk to make a practice of reminding session members of their assigned action items between meetings.
3. **Send moderator-reviewed minutes to session members for review before the meeting at which they will be adopted.** Provide sufficient time for review. Avoid sending minutes out the day of the meeting where they are to be adopted. It is best to give a few days or a week for session members to review minutes and to provide you with any additional corrections prior to the meeting where they are to be adopted. When exactly you send minutes may depend on the preferences of the members and/or the moderator of your particular session.
4. **Provide a copy of the reviewed minutes to the session at the meeting where they are to be adopted.**
5. **Help ensure that the session votes to adopt the reviewed minutes.** This most often happens at the beginning of a session meeting. It may occasionally happen via email.
6. **File newly adopted minutes with the permanent record of minutes immediately after the meeting where they are officially adopted.** For good filing practices, see **filing link…**

The same process outlined above can be used by the session to review and approve congregational meeting minutes as well.

## The Permanent Record

Once minutes are officially approved by the session, they need to be added to a permanent record which is stored on a computer. Minutes from each meeting should be stored in word processing files or PDF files, and they should be well organized. See the chapter on [Records Organization] for guidance on organizing your approved minutes.

## Examples

### Basic Minutes Template

We recommend clerks come to each meeting with a basic minutes outline already prepared. This will save time and distraction in the meeting itself. If the clerk has access to a meeting's agenda before the meeting, it is a good practice for him to prepare an outline for minutes based on that agenda.

The following template will be a helpful starting point:

::::: {.special}
Name of Church, Board, Committee, Commission, etc.  
Purpose of Meeting, often “Regular Scheduled Session Meeting”  
Time, Date, Year  
Location (and/or virtual app used for meeting remotely)

Present: Name (position related to body meeting), …

Excused absences: Name (position related to the body meeting), …

\1. ——— led devotions from ———, [brief summary]. ——— opened the meeting in prayer at #:## am/pm.
\2. Clerk’s business
   \a. Establishment of quorum
   \b. Adoption of previous meeting minutes
   \c. Recording of any actions taken by email between meetings, if applicable
   \d. Attendance, membership, statistics, etc.
   \e. Celebration of sacraments
      \i. Lord's Supper
      \ii. Baptisms
\3. Action item review
\4. Treasurer’s report
\5. Pastoral care
   \a. …
   \b. …

\#. …

\#. Next meeting set for [Time, Date, Year], at [Location]. ——— will lead devotions.

Meeting adjourned at #:## am/pm.

Respectfully submitted,  
———  
Stated Clerk (or Clerk pro tem)  
Name of Body Meeting
:::::

### Sample Sets of Meeting Minutes from Churches in Evangel Presbytery

1. Click **here** to download a sample set of **session meeting minutes**.
2. Click **here** to download a sample set of **congregational meeting minutes**.

<!--- 

## Optional Guidelines

For clerks (or moderators) who want to follow a more thorough set of standards for session minutes, we've provided the guidelines below. We note, however, that these guidelines are *not* required by the presbytery. They are simply offered as an optional aid for ensuring clarity, concision, and consistency.

1. At the beginning of each set of minutes, place a header on the left side, in the following format:

      > Name of Institution  
      Type of Meeting (including the specific body meeting)  
      Month, Date, YYYY, Time  
      Location of meeting (or name of software used if meeting was held virtually, e.g., "via Zoom")

   For a regular session meeting at Holy Trinity Reformed Church, the header would be as follows:

      > Holy Trinity Reformed Church  
      Regular Scheduled Session Meeting  
      October 11, 2012, 7:00pm  
      at Holy Trinity Reformed Church

3. Below the header (one line intervening), type “Present:”, followed by a list of all individuals in attendance at some point during the meeting. After each individual, put in parentheses his position/function in relation to the body meeting; for men with the same position, this may be put after all their names. Separate entries with a semicolon where it separates distinct positions; use a comma between names of the same position. Note these practices in the following example:

   > Present: John Owen (moderator); John Bunyan, Richard Baxter (associate pastors); Jeremy Taylor, Richard Sibbes, Jeremiah Burroughs (assistant pastors); Martin Luther, John Calvin, William Tyndale (elders); Philip Melanchthon (chairman, deacons board); Theodore Beza, Zacharias Ursinus, Jan Hus (deacons); Joshua Congrove (recording clerk); Thomas Aquinas, Clement of Rome (guests of session)

4. Below the previous list, type “Excused absences:”, followed by a list of all regular session members whose absences were excused by the moderator. If desired, type another line beginning with “Other absences:”, in which you list all absences not explicitly excused.

5. Below the prefatory material, and before enumeration of each item, place a paragraph summarizing when the meeting began, as well as the presenter, Scripture reference, and theme of the devotions. Then indicate who opened the meeting in prayer.

6. Minutes should be numbered according to topic. Sometimes, when multiple discussions or decisions happen on one topic, it’s best to use a general heading (e.g., "Baptism issues" or "Financial matters"), and then specific subheadings to organize the information. Other times, simply provide a sentence or two summarizing the discussion, and then place any action items beneath the relevant section.

   Note: When the minutes are compiled and revised, they should be grouped according to their proper topic, even if this does not match the chronology in which they occurred. For example, if discussion in the early part of the meeting concerned the financial matters of a particular committee of the church, and discussion later on dealt with appointments to that committee, these notes should be combined under an appropriate heading. Rarely, it’s useful to keep the notes separate if preserving the chronological order in which they were discussed is absolutely essential; but usually, it's least confusing to gather similar elements together.

7. The cardinal rule of taking minutes is to write enough, but not more. Crucial to include are **action items** (see below), **motions**, and **resolutions**. Helpful to include are sentences summarizing reports made by members (e.g., the financial report), and a brief statement of what was discussed (one or two sentences). Since minutes are properly intended to record only official actions of the board, please do not include opinions or consensus of the board or its individuals. The exception to this rule is when a member of the board would like his opposition to the session’s decision recorded in the minutes as a protest. In this case, however, he then needs to inform the entire board of his wish to record his opposition, and the moderator will help the recorder of the minutes to handle it properly.

   In addition, many decisions will be declared by the moderator to be "by consensus." Such decisions are to be recorded as official actions of the board, and should be prefaced with "By consensus" (see below). Unless so directed, do not write down the details of the discussion, nor the individual points made in the process. Record where the board finally arrives, not how they got there.

8. Below the relevant topic, indicate tasks assigned to individuals in the following format:

   > —NEW ACTION ITEM: Joe Schmoe will write a valediction to his name (copying elder Bob Smith on it), expressing his joy at being able to acquire a new designation.
   
   Make sure that action items contain all the necessary information for carrying out the assigned task. For example, an action item should never read as follows:
   
   > —NEW ACTION ITEM: Elder Jonathan Johnson will do the same as above.
      
   Instead, fully write out what Elder Jonathan Johnson is supposed to do, even if it means copying and pasting from another action item.

9. Record the names of anyone who takes significant action, to include motions, of course, but also action such as opening or closing in prayer. Often, if the action taken is informal or unanimous, you may also use "M/S/A" or "by consensus," depending on the nature of the action (and on whether you’re able to record the names fast enough!)

10. Votes in the negative do not need to be recorded unless requested by the voter, or unless the moderator so directs.

11. When recording names of individuals, always give the first and last name, unless that individual has been mentioned in a previous sentence of the same numbered item.

12. Do not hesitate to remind the moderator of his various duties if he overlooks them, particularly if they bear directly upon the minutes. Such duties include prayer at the open and close of the meeting, assigning action items to specific members of the board, ensuring that initial motions are given and seconded before proceeding with a vote, setting the time and place of the next meeting and who will give devotions, and so on.
 
13. If there is any more than one instance of orders of the day, sum the total number of minutes granted in aggregate, and express this in a single motion, e.g., "M/S/A for orders of the day for 45 minutes, in totality."

14. Supplemental documents: Documents that are approved by the board should only be referenced within the minutes themselves, and then appended inline below the body of the minutes. If documents are especially long or dependent upon formatting that may be lost in email form, you may also attach the original document as a PDF; regardless, documents must also be included inline.

15. Abbreviations for organizations or ministries of the church should only be used when clear and stated in full prior to their use. For example: The session received a report on New Geneva Academy (NGA) from Pastor Smith. He explained that NGA is working on…

16. Style: In general, our standard is Chicago Manual of Style. For commas, use the Oxford comma (i.e., including a comma before the final item in a list). Use only one space between sentences.

    Be scrupulous in your sentence structure, vocabulary, and style. Your goal is to produce a document in which the moderator will find nothing needing change. Likely you’ll never achieve that, but it’s something to aim for!

17. Concluding matter: Always include a statement about when and where the next meeting will be, and who will provide devotions. Then indicate when the meeting was adjourned, and by whose motion and prayer.

18. Below the body of the minutes, but before any supplemental documents, write the closing signature as follows:

    > Respectfully submitted,  
    Your Name
    Clerk of Session (or Clerk pro tem) 
    Name of Body Meeting
   
19. Separate the minutes proper from any supplemental appended documents with a row of asterisks or hyphens.

-->