# Keeping Minutes (Alex)

[From Evangel Presbytery Bylaws](https://docs.google.com/document/d/1WZ4PrWPCNPNsUEmfXLPNXCNJz5qaB09T3HXnCkPh2ak/edit?usp=sharing)

APPENDIX 1: GUIDELINES FOR KEEPING SESSION MINUTES

A. Session Minutes must include the following: 

A statement of the date, time, place, and purpose of the meeting (Stated, Called, adjourned stated, etc.) 
If the meeting is a called meeting the minutes must include the portion of the call that indicates the purpose of the meeting.
That the meeting was opened and closed with prayer. 
The names of all in attendance or absent from the meeting. 
That a quorum was present for the meeting. 
Communications received, and any action taken because of the communications. 
Approval of minutes from previous meetings. 
A statement that indicates the review and approval of the Diaconate minutes.
A statement that indicates the receiving of the Treasurer’s report as information. 
The actions of the Session including all the motions adopted and business transacted. 

B. When applicable, the minutes shall include the following:

A record of all covenant baptisms, baptisms upon profession of faith, and dates of the celebration of the Lord’s Supper.
Election of commissioners to presbytery. 
A record of the call and purpose for each congregational or corporation meeting.
A motion calling for the nomination and election of church officers.
A record of the officers nominated, trained and examined by the Session.
The December or the following January minutes must include a statement that records the pastor’s annual housing allowance approved by the Session.
The BCO requires Sessions to “...keep a fair record of baptisms, of those admitted to the Lord’s table, of non-communing members, and of the births, marriages, deaths, and dismissions of church members and of any baptisms and marriage ceremonies presided over by the pastors of the church outside its bounds” (BCO 14.8).
A copy of the approved operating budget and the yearly statistical report should be attached to December’s minutes. 

All minutes should be typed. They should be simple in word and in formatting. Email should be used when circulating minutes among members of the Session. The minutes should be included in the body of the email and not as an attachment. Once minutes have been officially adopted by the Session, they should be archived digitally using the PDF file format. To archive newly approved minutes, they should be added to the existing PDF archive. The pages should be consecutively numbered, leaving no blank pages between meetings and no records left out. As with all important digital documents, great care should be taken to ensure that Session minute archives have both local and remote backups. Sessions may keep a physical hard copy of their minutes in addition to their digital copy. If they choose to do so, however, they must ensure that the physical archives do not conflict with the digital ones.

C. After the Meeting:

Complete any necessary correspondence as required by actions taken by the Session.
Send transfer of the communicant’s membership certificates to other churches.
Update the church membership records as required by action of the Session (Additions, removals, etc.).
