# Membership Records

The clerk is responsible for keeping the rolls and registers of the church. The rolls are the official lists of members and the nature of their membership status. The registers are official lists of important occurrences in the life of the church and its members.

## Types of Membership 

Church membership in congregations of Evangel Presbytery consists of two types:

>**Communing** members are those who have made a profession of faith in Christ, have been baptized, and have been admitted by the Session to the Lord’s Table. The children of communing members are, through the covenant and by right of birth, **non-communing** members of the church. ([BCO 7](https://evangel.pressbooks.com/chapter/7-church-members/), emphasis added) 

Beyond this, individual congregations may specify further distinctions through their bylaws; for example, a church will commonly restrict voting privileges to communicant members over the age of 18. Or, churches may provide for *associate* members who have all the privileges of full members except for voting.

## Adding and Removing Members

As the clerk is charged with keeping the rolls and registers of the church, it falls to him to handle many membership processes. One such common process is the adding or removing of members to the rolls of the church. Particular steps will differ by individual church, but good guidelines for common procedures are as follows:

### A typical membership approval process

#. Individual expresses interest in membership.
#. Inquiry sent by individual to former church, asking for letter of good standing.
#. Membership interview takes place; if letter of good standing not yet received, elders inquire of home church.
#. If interviewing elders recommend membership, membership recommended to full session.
#. Session votes whether to approve membership (decision recorded in minutes).
#. Office notified; either office or interviewing elders inform member of decision.
#. Members give vows in front of congregation.
#. Letter of transfer sent to former church.
#. Clerk updates rolls and registers.

### A typical membership removal (non-transfer) process

#. Member requests removal.
#. Session determines whether removal is valid (i.e., if discipline process underway) (see [BCO 41.3](https://evangel.pressbooks.com/chapter/41-cases-without-process/) for other factors).
#. Session votes on removal.
#. Clerk sends letter of dismissal to former member.
#. Clerk updates registers.
    
### Membership removal process in case of excommunication

#. Judicatory recommends excommunication to full session (or carries it out itself, as a commission).
#. If required, session votes on excommunication.
#. Letter sent to former member. 
#. Clerk updates the register.
#. Announcement made to congregation.

### Membership removal without process in cases of non-attendance ([BCO 41.4](https://evangel.pressbooks.com/chapter/41-cases-without-process/))

#. Session reminds member of his vows and warn him of erasure from roll.
#. If no response after inquiry and due delay, session votes to erase member from roll.
#. Clerk sends letter of dismissal to former member.
#. Clerk updates the register.  

### Sending Letters

To speed the process of sending letters in the above procedures, a clerk may wish to use templates for commonly sent letters such as [responses to inquiries about good standing](https://github.com/Evangel-Presbytery/clerks-handbook/files/8682841/Good.standing.pdf), [transfer letters](https://github.com/Evangel-Presbytery/clerks-handbook/files/8682848/Transfer.notification.letter.pdf), [dismissal letters](https://github.com/Evangel-Presbytery/clerks-handbook/files/8682850/Membership.removal.for.non.attendance.template.pdf), [inquiries about membership status for members who relocate](https://github.com/Evangel-Presbytery/clerks-handbook/files/8682852/Member.relocated.attendance.inquiry.pdf), or [exhortations toward church attendance](https://github.com/Evangel-Presbytery/clerks-handbook/files/8682853/Attendance.inquiry.pdf). 

## Synchronization of Membership Records

A variety of methods may be used for keeping the rolls and registers. In all cases, however, care must be taken that the various methods are synchronized: that is, that changes are made among them all. If, for example, a church's roll is kept in a Microsoft Excel file but the church also uses a church management software (ChMS) or constituent relationship management software (CRM), the clerk must ensure that a change to the roll in one location is carried out in the others as well. Changes to membership are also to be kept in the minutes, which serve as the final and most authoritative record.

## Statistical Reports

Evangel's BCO requires that, once per year, each member church send along with its complete session minutes and annual budget a statistical report. (See [Submission of Records to Presbytery] and [Appendix\ 1 of the presbytery's bylaws](https://evangelpresbytery.com/wp-content/uploads/2021/06/EvangelPresbyteryBylaws_2021_06_03.pdf) for more information.) This report should include the following items, as applicable:

* Officers of the church
* All communicant members (with voting and non-voting members distinguished)
* All non-communicant members  
  
*All the following should include dates:*
* All new communicant and non-communicant members along with dates of their reception
* Births of members
* Baptisms (with infant baptisms and baptisms of those professing faith distinguished)
* Infant dedications
* Admissions of non-communing members to the Lord's Supper
* Dates of celebration of the Lord's Supper
* Dismissals from membership, including the reason (transfer, excommunication, etc.)
* Marriages of members
* Deaths of members
* Marriages and baptisms of non-members but performed by pastors of the church or on church grounds

If, as often, this report is presented for a congregation's annual meeting, it may also be useful to give statistics regarding the demographic change of the congregation over the previous year (e.g., percentage growth, a breakdown of the church by age group, etc.).

### Statistical Report Template {-}

To download a template which can be used for building your annual statistical report, choose one of the following file types: [.docx](https://clerks.evangelpresbytery.com/Church-Annual-Statistical-Report-Template.docx), [.doc], [.rtf], [.odt], [.pdf]. The template will need to be adapted to meet the needs of your particular church.