# Church Discipline Records

The Evangel Presbytery Book of Church Order addresses church discipline in [chapters 30-49](https://evangel.pressbooks.com/chapter/30-discipline-its-nature-subjects-and-ends/). This chapter exists to be a short-hand reference for clerks where *judicial process* is necessary (see [BCO 30.1](https://evangel.pressbooks.com/chapter/30-discipline-its-nature-subjects-and-ends/)). It pertains, in other words, to church discipline that is *formal* rather than *informal*. 

Clerks have specific duties in cases of discipline, and those duties are outlined below. Aside from their specific duties, clerks will often be called upon to help others understand disciplinary procedure. Clerks must understand both the theoretical and practical aspects of church discipline, and there is no substitute for carefully reading the entire section on church discipline in our BCO. This page is only meant to be a help, and the BCO always takes precedence.

## Overview

Informal discipline happens all the time in a healthy church. Formal process is necessary when one of the [censures](https://clerks.evangelpresbytery.com/church-discipline-records.html#church-censures) of the church may be called for in a disciplinary matter. In general, the process of formal discipline goes like this:

1. The court of jurisdiction (the local session or the presbytery) should hear charges against the accused, or establish a judiciary committee to do so. All charges brought before either the session or presbytery must be reduced to writing.
2. The judiciary should have their [first meeting](https://clerks.evangelpresbytery.com/church-discipline-records.html#the-first-meeting) and must send a written indictment to the accused.
3. No less than ten days after the indictment is served, the judiciary should meet a [second time](https://clerks.evangelpresbytery.com/church-discipline-records.html#second-meeting) with the accused present to read the charges and hear whether or not the accused pleads guilty.
4. No less than fourteen days later, the judiciary, along with the accused and all witnesses, should meet together for a [trial](https://clerks.evangelpresbytery.com/church-discipline-records.html#the-trial). Once the trial is complete, the clerk must assemble the "Record of the Case".
5. [Appeals](https://clerks.evangelpresbytery.com/church-discipline-records.html#appeals), if any, must be made in writing within thirty days of notification of the last court's decision.

## Duties of the Clerk

It is common in judicial proceedings for the session to appoint a judicial committee to work through the whole disciplinary process. The clerk should work closely with the judicial committee to ensure that all written materials pertaining to the proceedings are recorded and stored properly.

Overall, the Clerk's responsibility is to assemble the **Record of the Case**. It should include:

* the charges, 
* the answer, 
* the citations and returns thereto, and 
* the minutes of all meetings required in the process of formal discipline. The minutes of a trial should include the items listed above as well as the following:
  * all the testimony,
  * all such acts, orders, and decisions of the court relating to the case, as either party may desire, and 
  * the judgment. 

## General Principles

### Jurisdiction

As [stated earlier](https://clerks.evangelpresbytery.com/index.html#the-stated-clerk-defined), the BCO organizes Evangel Presbytery’s government into two types of “court,” church sessions and presbyteries ([BCO 12.1–2](https://evangel.pressbooks.com/chapter/12-church-courts-in-general/)). Original jurisdiction in relation to pastors pertains exclusively to the Presbytery, and in relation to other church members to the Session. If a Session is unable to try the person or persons accused, then the Presbytery has the right of jurisdiction.

### Offenses

As stated in [BCO 32.1](https://evangel.pressbooks.com/chapter/32-offenses/):

>An offense, the proper object of judicial process, is anything in the principles or practice of a church member professing faith in Christ, which is contrary to the Word of God.

### Church Censures

The [censures](https://evangel.pressbooks.com/chapter/33-church-censures/) which may be inflicted by church courts are:

* admonition, 
* suspension from the Sacraments, 
* suspension from office, 
* deposition from office, and 
* excommunication. 

### The Parties in Cases of Process

The original and only parties in a case of process are the accuser and the accused. The accuser is always Evangel Presbytery, whose honor and purity are to be maintained.

`IS THIS TRUE? Or is it also the local church, depending on the case?`

## Specific Steps in Judicial Process

### The First Meeting

Nothing should be done at the first meeting of the court, unless by consent of parties, except to:

* appoint a prosecutor, 
* write up the indictment,
* create a list of witnesses who support the indictment,
* send the indictment, and the list of supporting witnesses, to the accused and cite all parties and their witnesses to appear and be heard at another meeting. The second meeting should not be sooner than **ten days** after such citation.

Indictments and citations should be delivered in person or in another manner providing verification of the date of receipt. In drawing the indictment, the times, places, and circumstances should be stated clearly so that the accused has an opportunity to make his defense.

### Second Meeting

At the second meeting of the court, the charges should be read to the accused and he should be asked whether he pleads guilty or not. If he confesses, the court may deal with him as it sees fit. If he pleads "not guilty", then the trial should be scheduled and all parties and their witnesses should be cited to appear. The trial should not be sooner than fourteen (14) days after the citation.

### The Trial

The following order should be observed at any trial: 

1. The moderator should charge the court. [WHAT DOES THAT MEAN?]
2. The indictment should be read, and the accused should be given the opportunity to answer.
3. The witnesses for the prosecutor and then those for the accused should be examined. 
4. The prosecutor should be heard first, and then the accused, and then prosecutor should close. 
5. The roll shall be called, and the members may express their opinion in the cause. [NOT ENTIRELY SURE WHAT THIS STEP IS, EITHER.]
6. The vote shall be taken [WHO IS ACTUALLY VOTING IN THIS CASE?], the verdict announced and judgment entered on the records.

### Appeals

An appeal is the transfer to a higher court of a judicial case on which judgment has been rendered in a lower court, and is allowable only to the party against whom the decision has been rendered.

An appeal cannot be made to any court other than the next higher, except with its consent.

Only those who have submitted to a regular trial are entitled to an appeal. Those who have not submitted to a regular trial are not entitled to an appeal.

The grounds of appeal are such as the following: 

* any irregularity in the proceedings of the lower court; 
* refusal of reasonable indulgence to a party on trial; 
* receiving improper, or declining to receive proper, evidence; 
* hurrying to a decision before all the testimony is taken; 
* manifestation of prejudice in the case; and 
* mistake or injustice in the judgment and censure.

Written appeals must be filed with both the clerk of the lower court and the clerk of the higher court, **within thirty days of notification of the last court’s decision**.

The clerk of the lower court must file a copy of all proceedings in connection with the case with the clerk of the higher court not more than thirty (30) days after receipt of notice of appeal.