# Submission of Records to Presbytery

Each session is required by [BCO 43](https://evangel.pressbooks.com/chapter/43-general-review-and-control/) to submit its minutes to the presbytery once per year for review. This review is handled through Evangel's permanent Sessional Records Committee (SRC). The SRC sets a rotating schedule for when each church is assigned to submit its records and will commuicate with you about when your records are due.

The presbytery has established official standards for submitting records which can be found in the [bylaws](https://evangelpresbytery.com/wp-content/uploads/2021/06/EvangelPresbyteryBylaws_2021_06_03.pdf), which also include more detailed information about the work of the SRC. The following information is provided as an extra resource to help you understand the process of submitting records, and to help reduce errors in the preparation and submission of records.

## What to Include

1. **Session meeting minutes *and* congregational meeting minutes** in chronological order in one PDF file. For more information, see the chapter on [Keeping Minutes].
2. **Annual statistical report** as a separate PDF file. For more information, see [Membership Records].
3. **Adopted annual budget** as a separate PDF file.

## What *Not* to Include

* Adopted minutes from previous meetings as attachments to the minutes of meetings where they were adopted. Please only include one copy of each set of officially adopted minutes per meeting.
* Monthly financial/treasurer reports.
* Ministry proposals presented at session meetings (but do include resolutions, statements, or actions related to such proposals as adopted or acted on by the session).
* Full committee/subcommittee/commission reports; just record actions taken regarding any proposals, or actions taken by a commission.
* Deacons’ minutes.

## Formatting

Evangel's bylaws require that minutes be submitted in PDF format with numbered pages. We recommend the following:

1. Copy and paste all minutes (from session meetings *and* congregational meetings) into a single document in Microsoft Word or another word processing application.
2. Clearly separate each set of minutes with plenty of extra space and a row of asterisks (\*\*\*\*).
3. Use the application's automatic page numbering feature to add page numbers to the entire document.
4. Save (or Export, in some apps) the document as a PDF.

## After Review

After the Sessional Records Committee has reviewed your records, they will return them to you with comments.

### Types of Exception

Comments from the SRC will generally be to indicate "exceptions," of which there are three types:

* **Notations**, defined in Evangel's bylaws as "typographical errors, misspellings, improper punctuation, and other minor variations in form and clarity" (6(D)(6)).
* **Exceptions of Form**, defined in Evangel's bylaws as "violations of Evangel Presbytery's Guidelines for Keeping Session Minutes or violations of rules of order" (ibid.).
* **Exceptions of Substance**, defined in Evangel's bylaws as "apparent violations of the Sctipture or serious irregularities from the Constitution of Evangel Presbytery, actions out of accord with the deliverances of the Presbytery, and matters of impropriety and important delinquencies" (ibid.).

### Correcting Exceptions

* **Notations**, whenever possible, should be corrected in the minutes. Such corrections typically do not require review or action by the session, since they are usually typographical in nature and therefore do not affect the meaning of what was recorded.
* **Exceptions of form** should also be corrected in the minutes when possible. These corrections may sometimes require review and action from the board, especially if the corrections will substantially change the meaning of something which was recorded in the minutes. Use discretion.
* **Exceptions of substance** are referred by the SRC to the presbytery so that the presbytery as a whole can decide how to address the error, and whether to pursue a more formal process of discipline. Exceptions of substance *must* be corrected by the session, unless the session can demonstrate that the exception of substance was given in error. See [section\ 6 of Evangel's bylaws](https://evangelpresbytery.com/wp-content/uploads/2021/06/EvangelPresbyteryBylaws_2021_06_03.pdf) for more information.

### When *Not* to Correct Minutes

When an exception of form or an exception of substance results from an **error on the part of the session**, and the minutes accurately record the session's error, there is nothing to correct in the minutes. Depending on the circumstances, official action on the part of the session *may* be required to correct its error, but that might not always be possible. For example, if a session failed to give the congregation adequate notice about a congregational meeting, and yet the meeting still took place, this would be an exception of form, but the session cannot go back and undo the violation of good order. An exception of form from the SRC in this case is a reminder to the session to make sure that it does its work properly in the future. (In cases where good order has been violated, it is often prudent for the session to acknowledge its failure to at least those directly affected by the violation. Furthermore, it is wise to record such an acknowledgment in the minutes.)

### Apparent Violations

At other times, the minutes, due to a lack of clarity, might indicate an **apparent exception** where no violation was actually committed by the session. If this is the case, the SRC will typically recommend clarifying the minutes so that they more accurately reflect what happened. It's ultimately up to the session to decide whether to correct its minutes in this case, but the session should understand that leaving the records unclear may result in problems for itself down the road. Since this kind of error is usually more than just typographical, it is a good idea for the session to formally adopt an amendment to its previously approved minutes.

### Recommendations

The SRC will sometimes provide **recommendations** on how you can improve the [clarity](#clarity), [concision](#concision), or [consistency](#consistency) of your minutes. These are merely recommendations and do not require correction. They are offered as an aid to making your minutes more useful to your own session.
