project:
  type: book

book:
  title: "Handbook for Evangel Presbytery Clerks"
  author: "Office of the Stated Clerk of Evangel Presbytery"
  repo-url: https://github.com/Evangel-Presbytery/clerks-handbook
  chapters:
    - index.qmd
    - 02-governing-documents.qmd
    - 03-keeping-minutes.qmd
    - 04-membership-records.qmd
    - 05-church-discipline-records.qmd
    - 06-organization-of-records.qmd
    - 07-submission-of-records-to-presbytery.qmd
    - 08-roberts-rules-of-order-for-clerks.qmd
  sidebar:
    header: TOCheader.qmd
    search: true
  favicon: "evangel-favicon-196.png"

format:
  html:
    css: "style.css"
    include-in-header:
      - text: <script src="https://kit.fontawesome.com/c2565ebea9.js" crossorigin="anonymous"></script>
