project:
  type: book

book:
  sidebar:
    header: TOCheader.qmd
    title: false
    search: true
  title: "Handbook for Evangel Presbytery Clerks"
  author: "Office of the Stated Clerk of Evangel Presbytery"
  date: today
  repo-url: https://github.com/Evangel-Presbytery/clerks-handbook
  favicon: "evangel-favicon-196.png"
  chapters:
    - index.qmd
    - 02-governing-documents.qmd
    - 03-keeping-minutes.qmd
    - 04-membership-records.qmd
    - 05-church-discipline-records.qmd
    - 06-organization-of-records.qmd
    - 07-submission-of-records-to-presbytery.qmd
    - 08-roberts-rules-of-order-for-clerks.qmd

format:
  html:
    css: "style.css"

